name: 'kishorekmtest12 '
description: 'kishore tsc test'
author: 'kishore'
inputs:
  milliseconds: # change this
    required: true
    description: 'time to wait in ms'
    default: '1000'
runs:
  using: 'node16'
  main: 'dist/index.js'
